### ISSUE TITLE
Multiple Transactions (BAD_ACCESS)

### ISSUE THREAD

**Issue by MatthewYork** [bennyguitar/SatelliteStore#1]
Hey, Ben,

Whenever you try to do multiple transactions in the same run, sometimes the second or later transaction can trigger a notification to an object that has already been dealloced through arc. Found this out when trying to implement SatelliteStore earlier today.

I have it all fixed where it doesn't crash anymore, so I will be asking initiating a pull request soon with the changes.

Hope all is well,

-Matt

**Comment by bennyguitar** [comment]
Ahh very interesting. I had a hunch that might be the case - looking forward to the pull request.
